In [23]:
import numpy as np

In [24]:
a = np.array([1,2,3])
b = np.array([[4,5,6],[7,8,9]])

c = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])

In [25]:
print(b.ndim) #gets dimensions

2


In [26]:
#get specific element [row,column]
b[0,2] #gets 6

6

In [27]:
#get specific row
b[0,:] #gets column and whole row

array([4, 5, 6])

In [28]:
#get a column
b[:,0]#gets all column of row
#justing using : gets all of that type, in this case all rows

array([4, 7])

In [29]:
#get by step [row,startindex:endindex:stepsize]
c[0,1:6:2] #0-6 every second elem, selecting from row 0

array([2, 4, 6])

In [30]:
b[0,1]=20
print(b)

[[ 4 20  6]
 [ 7  8  9]]


In [31]:
#replace whole column
b[:,2] = 5 #all rows, only the second column
print(b)

[[ 4 20  5]
 [ 7  8  5]]


In [46]:
#3d arr
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

d[0,0,0] #works outside in
#d[0][0][0]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


1

In [47]:
#replacing
d[:,1,:] = [[8,8],[9,9]]#replaces by dimension, so the second array in the first array gets replaced with [8,8] and the second array in the second array gets replaced with [9,9]
print(d)

[[[1 2]
  [8 8]]

 [[5 6]
  [9 9]]]


#Initing Arrays

In [50]:
#all zeros
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [51]:
print(np.ones((2,2,3)))

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [53]:
print(np.full((2,2),99))

[[99 99]
 [99 99]]


In [54]:
#any other number full_like
print(np.full_like(d,4)) #makes an array the same shape as 4

[[[4 4]
  [4 4]]

 [[4 4]
  [4 4]]]


In [56]:
#matrix of random decimal nums
print(np.random.rand(4,2)) #rows, cols

[[0.47423524 0.36753801]
 [0.92293146 0.03441876]
 [0.94600746 0.45500712]
 [0.67418675 0.76994765]]


In [60]:
#rand ints
print(np.random.randint(7,size=(4,2))) #4x2 0-6(does not include 7)

[[3 3]
 [6 0]
 [1 0]
 [0 1]]


In [62]:
#identity matrix
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [69]:
#repeating arrays
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)#axis 0 is rows, 1 repeats it across the column 
print(r1)



[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [71]:
r2 = np.repeat(arr,3,axis=1)
print(r2)

[[1 1 1 2 2 2 3 3 3]]
